// SPDX-License-Identifier: MIT
// Hand-written designer for the main dashboard. Builds the sidebar nav, the
// 6 content pages (Status / Alerts / AI Threats / Settings / Logs / Console)
// and every static control. Code-behind file (DashboardForm.cs) handles the
// dynamic logic.
//
// This file is treated as auto-generated by the C# compiler because of the
// .Designer.cs naming convention. The `#nullable` directive below silences
// the CS8669 warnings that would otherwise fire on every `string?` field.

#nullable enable annotations

using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Windows.Forms;
using WhitehatSecurity.Core;

namespace WhitehatSecurity.Ui;

public sealed partial class DashboardForm
{
    private Panel?        _sidebar;
    private Panel?        _content;
    private readonly Dictionary<string, Button> _navButtons = new();

    private void InitializeComponent()
    {
        SuspendLayout();

        // ---------------- Form ----------------
        Text          = "Whitehat Security Dashboard";
        Size          = new Size(1080, 720);
        StartPosition = FormStartPosition.CenterScreen;
        BackColor     = Theme.Bg;
        ForeColor     = Theme.TextMain;
        Font          = Theme.Body();
        MinimumSize   = new Size(960, 600);

        // ---------------- Sidebar ----------------
        _sidebar = new Panel
        {
            Dock      = DockStyle.Left,
            Width     = 200,
            BackColor = Theme.Sidebar,
            Padding   = new Padding(0, 12, 0, 12),
        };
        Controls.Add(_sidebar);

        var logo = new Label
        {
            Text      = "Whitehat Security",
            ForeColor = Theme.Accent,
            Font      = new Font("Segoe UI", 13, FontStyle.Bold),
            AutoSize  = false,
            TextAlign = ContentAlignment.MiddleCenter,
            Dock      = DockStyle.Top,
            Height    = 36,
        };
        var version = new Label
        {
            Text      = "v7.2 Dashboard",
            ForeColor = Theme.TextDim,
            Font      = new Font("Segoe UI", 8),
            AutoSize  = false,
            TextAlign = ContentAlignment.MiddleCenter,
            Dock      = DockStyle.Top,
            Height    = 20,
        };
        _sidebar.Controls.Add(version);
        _sidebar.Controls.Add(logo);

        // Add a small spacer between header and nav buttons
        _sidebar.Controls.Add(new Panel { Dock = DockStyle.Top, Height = 16, BackColor = Theme.Sidebar });

        // ---------------- Content host ----------------
        _content = new Panel
        {
            Dock      = DockStyle.Fill,
            BackColor = Theme.Bg,
            Padding   = new Padding(20),
        };
        Controls.Add(_content);
        _content.BringToFront();

        // ---------------- Pages (built before nav buttons so we can wire them) ----------------
        _navPages["Status"]    = BuildStatusPage();
        _navPages["Alerts"]    = BuildAlertsPage();
        _navPages["AI"]        = BuildAiThreatsPage();
        _navPages["Settings"]  = BuildSettingsPage();
        _navPages["Logs"]      = BuildLogsPage();
        _navPages["Console"]   = BuildConsolePage();

        foreach (var page in _navPages.Values)
        {
            page.Dock     = DockStyle.Fill;
            page.Visible  = false;
            _content.Controls.Add(page);
        }

        // ---------------- Sidebar nav buttons ----------------
        // Buttons are added top-to-bottom; we add in reverse order so the
        // top-of-list ends up at the top of the Dock=Top stack.
        AddNavButton("Console", "[>]  Console");
        AddNavButton("Logs",    "[L]  Logs");
        AddNavButton("Settings","[C]  Settings");
        AddNavButton("AI",      "[AI] AI Threats");
        AddNavButton("Alerts",  "[A]  Alerts");
        AddNavButton("Status",  "[S]  Status");

        // Default page
        ShowPage("Status");

        ResumeLayout(false);
    }

    private void AddNavButton(string key, string label)
    {
        var btn = new Button
        {
            Text       = label,
            Dock       = DockStyle.Top,
            Height     = 40,
            FlatStyle  = FlatStyle.Flat,
            BackColor  = Theme.Sidebar,
            ForeColor  = Theme.TextMain,
            Font       = Theme.NavBtn(),
            TextAlign  = ContentAlignment.MiddleLeft,
            Padding    = new Padding(16, 0, 0, 0),
            Cursor     = Cursors.Hand,
            Tag        = key,
        };
        btn.FlatAppearance.BorderSize        = 0;
        btn.FlatAppearance.MouseOverBackColor = Theme.BtnHover;
        btn.Click += (_, _) => ShowPage(key);
        _sidebar!.Controls.Add(btn);
        _navButtons[key] = btn;
    }

    private void ShowPage(string key)
    {
        foreach (var (k, page) in _navPages)
            page.Visible = (k == key);

        // Highlight the active nav button
        foreach (var (k, btn) in _navButtons)
            btn.BackColor = (k == key) ? Theme.BtnHover : Theme.Sidebar;
    }

    /// <summary>
    /// Public entry point used by TrayApplicationContext to switch tabs from
    /// the system-tray context menu.
    /// </summary>
    public void OpenTab(string key)
    {
        if (_navPages.ContainsKey(key)) ShowPage(key);
    }

    // ============================================================================
    //  PAGE 1: STATUS
    // ============================================================================
    private Panel BuildStatusPage()
    {
        var page = new Panel { BackColor = Theme.Bg, AutoScroll = true };

        var title = new Label
        {
            Text      = "Live Monitoring Status",
            Font      = Theme.PageTitle(),
            ForeColor = Theme.Accent,
            AutoSize  = true,
            Location  = new Point(8, 8),
        };
        page.Controls.Add(title);

        // Stat cards — keep references to the value labels so RefreshStatusPage
        // can update them on every tick.
        var (alertCard, alertVal) = BuildStatCard("TOTAL ALERTS", "0",     Theme.Red,    new Point(8,   60));
        var (connCard,  connVal)  = BuildStatCard("CONNECTIONS",  "0",     Theme.Accent, new Point(220, 60));
        var (procCard,  procVal)  = BuildStatCard("PROCESSES",    "0",     Theme.Green,  new Point(432, 60));
        var (upCard,    upVal)    = BuildStatCard("UPTIME",       "00:00", Theme.Orange, new Point(644, 60));
        page.Controls.AddRange(new Control[] { alertCard, connCard, procCard, upCard });
        _alertCountValue = alertVal;
        _connCountValue  = connVal;
        _procCountValue  = procVal;
        _uptimeValue     = upVal;

        // Computer info card
        var info = new Panel
        {
            Location  = new Point(8, 165),
            Size      = new Size(848, 70),
            BackColor = Theme.Card,
        };
        var infoLine = new Label
        {
            Text =
                $"Computer: {Environment.MachineName}    " +
                $"User: {Environment.UserName}    " +
                $"Started: {DateTime.Now:HH:mm:ss}    " +
                $"Architecture: {(Environment.Is64BitProcess ? "x64" : "x86")}",
            Font      = Theme.Mono(9, FontStyle.Bold),
            ForeColor = Theme.TextMain,
            AutoSize  = true,
            Location  = new Point(16, 24),
        };
        info.Controls.Add(infoLine);
        page.Controls.Add(info);

        // Security posture row
        var postureTitle = new Label
        {
            Text      = "Security Posture",
            Font      = new Font("Segoe UI", 10, FontStyle.Bold),
            ForeColor = Theme.Accent,
            AutoSize  = true,
            Location  = new Point(8, 250),
        };
        page.Controls.Add(postureTitle);

        var postureCard = new Panel
        {
            Location  = new Point(8, 275),
            Size      = new Size(848, 80),
            BackColor = Theme.Card,
        };
        var postureLabels = new (string text, Color dot)[]
        {
            ("Defender",  Theme.PostureGood),
            ("Firewall",  Theme.PostureGood),
            ("UAC",       Theme.PostureGood),
            ("RDP",       Theme.PostureGood),
            ("SecureBoot",Theme.PostureGood),
            ("TPM",       Theme.PostureGood),
            ("HVCI",      Theme.PostureNa),
            ("BitLocker", Theme.PostureNa),
        };
        for (int i = 0; i < postureLabels.Length; i++)
        {
            int col = i % 4;
            int row = i / 4;
            var lbl = new Label
            {
                Text      = "● " + postureLabels[i].text,
                ForeColor = postureLabels[i].dot,
                Font      = new Font("Segoe UI", 9, FontStyle.Bold),
                AutoSize  = true,
                Location  = new Point(20 + col * 200, 18 + row * 28),
            };
            postureCard.Controls.Add(lbl);
        }
        page.Controls.Add(postureCard);

        // Recent alerts list
        var recentTitle = new Label
        {
            Text      = "Recent Alerts",
            Font      = new Font("Segoe UI", 10, FontStyle.Bold),
            ForeColor = Theme.Accent,
            AutoSize  = true,
            Location  = new Point(8, 370),
        };
        page.Controls.Add(recentTitle);

        _recentList.Location      = new Point(8, 395);
        _recentList.Size          = new Size(848, 250);
        _recentList.View          = View.Details;
        _recentList.FullRowSelect = true;
        _recentList.GridLines     = false;
        _recentList.BackColor     = Theme.Card;
        _recentList.ForeColor     = Theme.BodyText;
        _recentList.Font          = Theme.Mono(9);
        _recentList.HeaderStyle   = ColumnHeaderStyle.Nonclickable;
        _recentList.Columns.Add("Time",     90);
        _recentList.Columns.Add("Severity", 70);
        _recentList.Columns.Add("Category", 110);
        _recentList.Columns.Add("Title",    540);
        page.Controls.Add(_recentList);

        return page;
    }

    /// <summary>
    /// Builds one of the four big stat cards on the Status page. Returns the
    /// card panel and the inner Label that holds the metric so the
    /// code-behind can update it on every tick.
    /// </summary>
    private (Panel card, Label valueLabel) BuildStatCard(
        string headerText, string initialValue, Color accent, Point location)
    {
        var card = new Panel
        {
            Size      = new Size(200, 90),
            BackColor = Theme.Card,
            Location  = location,
            Cursor    = Cursors.Hand,
        };
        var bar = new Panel
        {
            Dock      = DockStyle.Left,
            Width     = 4,
            BackColor = accent,
        };
        card.Controls.Add(bar);

        var header = new Label
        {
            Text      = headerText,
            Font      = Theme.CardLabel(),
            ForeColor = Theme.TextDim,
            AutoSize  = true,
            Location  = new Point(16, 14),
        };
        var value = new Label
        {
            Text      = initialValue,
            Font      = Theme.CardValue(),
            ForeColor = Theme.TextMain,
            AutoSize  = true,
            Location  = new Point(16, 32),
        };
        card.Controls.Add(header);
        card.Controls.Add(value);

        // Hover effect
        void Hover(object? s, EventArgs e) => card.BackColor = Theme.CardHover;
        void Leave(object? s, EventArgs e) => card.BackColor = Theme.Card;
        card.MouseEnter   += Hover; card.MouseLeave   += Leave;
        header.MouseEnter += Hover; header.MouseLeave += Leave;
        value.MouseEnter  += Hover; value.MouseLeave  += Leave;

        return (card, value);
    }

    // ============================================================================
    //  PAGE 2: ALERTS
    // ============================================================================
    private Panel BuildAlertsPage()
    {
        var page = new Panel { BackColor = Theme.Bg };

        var title = new Label
        {
            Text      = "Alert History",
            Font      = Theme.PageTitle(),
            ForeColor = Theme.Red,
            AutoSize  = true,
            Location  = new Point(8, 8),
        };
        page.Controls.Add(title);

        // Alerts list
        _alertsList.Location      = new Point(8, 60);
        _alertsList.Size          = new Size(540, 580);
        _alertsList.Anchor        = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left;
        _alertsList.View          = View.Details;
        _alertsList.FullRowSelect = true;
        _alertsList.GridLines     = false;
        _alertsList.BackColor     = Theme.Card;
        _alertsList.ForeColor     = Theme.BodyText;
        _alertsList.Font          = Theme.Mono(9);
        _alertsList.HeaderStyle   = ColumnHeaderStyle.Nonclickable;
        _alertsList.Columns.Add("Time",     85);
        _alertsList.Columns.Add("Severity", 65);
        _alertsList.Columns.Add("Category", 95);
        _alertsList.Columns.Add("Title",    140);
        _alertsList.Columns.Add("Message",  140);
        _alertsList.SelectedIndexChanged += OnAlertSelected;
        page.Controls.Add(_alertsList);

        // Detail panel on the right
        _alertDetail.Location  = new Point(560, 60);
        _alertDetail.Size      = new Size(490, 580);
        _alertDetail.BackColor = Theme.Card;
        _alertDetail.Anchor    = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;

        _alertDetailTitle.Text      = "Select an alert to view details";
        _alertDetailTitle.Font      = new Font("Segoe UI", 12, FontStyle.Bold);
        _alertDetailTitle.ForeColor = Theme.TextDim;
        _alertDetailTitle.Location  = new Point(16, 16);
        _alertDetailTitle.Size      = new Size(460, 24);
        _alertDetail.Controls.Add(_alertDetailTitle);

        _alertDetailBody.Location   = new Point(16, 50);
        _alertDetailBody.Size       = new Size(460, 360);
        _alertDetailBody.Multiline  = true;
        _alertDetailBody.ReadOnly   = true;
        _alertDetailBody.ScrollBars = ScrollBars.Vertical;
        _alertDetailBody.BackColor  = Theme.Card;
        _alertDetailBody.ForeColor  = Theme.TextMain;
        _alertDetailBody.Font       = Theme.Mono(9);
        _alertDetailBody.BorderStyle = BorderStyle.None;
        _alertDetail.Controls.Add(_alertDetailBody);

        // Action buttons
        StyleActionButton(_btnIpLookup,    "IP Lookup",     new Point(16, 430), 110);
        _btnIpLookup.Click   += OnIpLookupClick;
        StyleActionButton(_btnOpenLog,     "Open Log",      new Point(132, 430), 110);
        _btnOpenLog.Click    += OnOpenLogClick;
        StyleActionButton(_btnRegedit,     "Open Regedit",  new Point(248, 430), 110);
        _btnRegedit.Click    += OnRegeditClick;
        StyleActionButton(_btnBlockIp,     "Block IP (FW)", new Point(16, 470), 226);
        _btnBlockIp.Click    += OnBlockIpClick;
        StyleActionButton(_btnKillProcess, "Kill PID",      new Point(248, 470), 226);
        _btnKillProcess.Click += OnKillProcessClick;
        _alertDetail.Controls.Add(_btnIpLookup);
        _alertDetail.Controls.Add(_btnOpenLog);
        _alertDetail.Controls.Add(_btnRegedit);
        _alertDetail.Controls.Add(_btnBlockIp);
        _alertDetail.Controls.Add(_btnKillProcess);

        page.Controls.Add(_alertDetail);

        // Hide all action buttons until an alert is selected
        ClearAlertDetail();

        return page;
    }

    private static void StyleActionButton(Button btn, string text, Point loc, int width)
    {
        btn.Text       = text;
        btn.Location   = loc;
        btn.Size       = new Size(width, 32);
        btn.FlatStyle  = FlatStyle.Flat;
        btn.BackColor  = Theme.BtnHover;
        btn.ForeColor  = Theme.TextMain;
        btn.Font       = new Font("Segoe UI", 9, FontStyle.Bold);
        btn.Cursor     = Cursors.Hand;
        btn.FlatAppearance.BorderSize = 0;
        btn.Visible    = false;
    }

    // ============================================================================
    //  PAGE 3: AI THREATS  (placeholder — full engine wiring is a future task)
    // ============================================================================
    private Panel BuildAiThreatsPage()
    {
        var page = new Panel { BackColor = Theme.Bg };

        var title = new Label
        {
            Text      = "AI Threat Detection",
            Font      = Theme.PageTitle(),
            ForeColor = Theme.Purple,
            AutoSize  = true,
            Location  = new Point(8, 8),
        };
        page.Controls.Add(title);

        var subtitle = new Label
        {
            Text =
                "Will run an 8-engine scan: Memory, Behavioral, SecureBoot/TPM, BYOVD,\n" +
                "Hidden Process, ETW, Driver Integrity, Hypervisor.\n\n" +
                "The 8 engines themselves are queued as a follow-up port — the page is\n" +
                "in place so the layout is preserved and the wiring is ready.",
            Font      = Theme.Body(10),
            ForeColor = Theme.TextDim,
            AutoSize  = true,
            Location  = new Point(8, 50),
        };
        page.Controls.Add(subtitle);

        var scanBtn = new Button
        {
            Text      = "Scan Now",
            Location  = new Point(8, 160),
            Size      = new Size(140, 36),
            FlatStyle = FlatStyle.Flat,
            BackColor = Theme.Purple,
            ForeColor = Theme.TextMain,
            Font      = new Font("Segoe UI", 10, FontStyle.Bold),
            Enabled   = false,
        };
        scanBtn.FlatAppearance.BorderSize = 0;
        page.Controls.Add(scanBtn);

        return page;
    }

    // ============================================================================
    //  PAGE 4: SETTINGS  (27 toggles)
    // ============================================================================
    private Panel BuildSettingsPage()
    {
        var page = new Panel
        {
            BackColor  = Theme.Bg,
            AutoScroll = true,
        };

        int y = 8;

        // -------- Header --------
        var title = new Label
        {
            Text      = "Settings",
            Font      = Theme.PageTitle(),
            ForeColor = Theme.Accent,
            AutoSize  = true,
            Location  = new Point(8, y),
        };
        page.Controls.Add(title);
        y += 36;

        var subtitle = new Label
        {
            Text      = "Toggle which findings raise notifications. Changes save automatically. Items marked [admin] trigger UAC.",
            Font      = Theme.Body(9),
            ForeColor = Theme.TextDim,
            AutoSize  = true,
            Location  = new Point(8, y),
        };
        page.Controls.Add(subtitle);
        y += 30;

        // -------- Notification Categories section --------
        y = AddSectionHeader(page, "Notification Categories", y);
        var categories = new (string Key, string Label, string Desc)[]
        {
            ("Firmware",   "Firmware Integrity Changes",   "Driver/firmware file hash modifications, deletions, new files"),
            ("Driver",     "Driver Changes",               "New drivers loaded or existing drivers removed"),
            ("Service",    "New Services",                 "Newly installed or registered Windows services"),
            ("Connection", "Unknown Network Connections",  "Outbound connections from unrecognized processes (off by default — noisy)"),
            ("Process",    "Unsigned Processes",           "New processes running without a valid digital signature"),
            ("Listener",   "New Listening Ports",          "New ports opened for incoming connections"),
            ("Registry",   "Registry Startup Key Changes", "Modifications to Run/RunOnce and tamper-protection keys"),
            ("Security",   "Security Events",              "Remote logons, failed logins, new accounts"),
            ("RDP",        "Remote Desktop (RDP) Status",  "Alert when Remote Desktop is enabled"),
            ("Hosts",      "Hosts File Modifications",     "Changes to the hosts file that could redirect DNS"),
        };
        foreach (var c in categories)
            y = AddSettingCheckbox(page, c.Key, c.Label, c.Desc, _config.IsCategoryEnabled(c.Key), y);

        // -------- Display section --------
        y = AddSectionHeader(page, "Display & Behavior", y + 8);
        y = AddSettingCheckbox(page, "ShowThreatDetails",        "Detailed Threat Info",          "Show full details and severity levels for threats", _config.ShowThreatDetails,        y);
        y = AddSettingCheckbox(page, "EnableToastNotifications", "Enable Toast Notifications",    "Show Windows toast/balloon notifications for alerts", _config.EnableToastNotifications, y);
        y = AddSettingCheckbox(page, "BeepOnAlert",              "Beep on Alert",                 "Play system beep when alerts occur", _config.BeepOnAlert, y);

        // -------- Firewall Profiles --------
        y = AddSectionHeader(page, "Firewall Profiles  [admin]", y + 8);
        y = AddSettingCheckbox(page, "FW_DomainProfile",  "Domain Firewall Profile",  "Enable Windows Firewall for domain networks",        _config.FW_DomainProfile,  y);
        y = AddSettingCheckbox(page, "FW_PrivateProfile", "Private Firewall Profile", "Enable Windows Firewall for private/home networks",  _config.FW_PrivateProfile, y);
        y = AddSettingCheckbox(page, "FW_PublicProfile",  "Public Firewall Profile",  "Enable Windows Firewall for public networks",        _config.FW_PublicProfile,  y);

        // -------- Firewall Block Rules --------
        y = AddSectionHeader(page, "Firewall Block Rules  [admin]", y + 8);
        y = AddSettingCheckbox(page, "FW_BlockInbound",  "Block All Inbound",   "Block all incoming connections except explicitly allowed", _config.FW_BlockInbound,  y);
        y = AddSettingCheckbox(page, "FW_BlockOutbound", "Block All Outbound",  "Block all outgoing connections (strict — may break apps)", _config.FW_BlockOutbound, y);
        y = AddSettingCheckbox(page, "FW_BlockPing",     "Block ICMP Ping",     "Block incoming ping requests",                              _config.FW_BlockPing,     y);
        y = AddSettingCheckbox(page, "FW_BlockLAN",      "Block LAN Traffic",   "Block all local network traffic",                           _config.FW_BlockLAN,      y);
        y = AddSettingCheckbox(page, "FW_BlockDevices",  "Block Device Discovery", "Block SMB / NetBIOS / LLMNR / mDNS",                     _config.FW_BlockDevices,  y);

        // -------- Host-Based Protection --------
        y = AddSectionHeader(page, "Host-Based Protection  [admin]", y + 8);
        y = AddSettingCheckbox(page, "PF_BlockTrackers",  "Block Trackers",     "Block known tracking domains via hosts file",          _config.PF_BlockTrackers,  y);
        y = AddSettingCheckbox(page, "PF_BlockMalware",   "Block Malware",      "Block known malware domains via hosts file",            _config.PF_BlockMalware,   y);
        y = AddSettingCheckbox(page, "PF_BlockTelemetry", "Block Telemetry",    "Block Windows and third-party telemetry domains",       _config.PF_BlockTelemetry, y);
        y = AddSettingCheckbox(page, "PF_BlockDNSBypass", "Prevent DNS Bypass", "Lock port 53 - block DNS traffic except configured DNS", _config.PF_BlockDNSBypass, y);

        // -------- DNS section --------
        y = AddSectionHeader(page, "DNS & Secure DNS  [admin]", y + 8);
        var dnsLabel = new Label
        {
            Text      = "DNS Provider:",
            Font      = new Font("Segoe UI", 10, FontStyle.Bold),
            ForeColor = Theme.TextMain,
            AutoSize  = true,
            Location  = new Point(20, y + 6),
        };
        page.Controls.Add(dnsLabel);
        var dnsCombo = new ComboBox
        {
            Location      = new Point(160, y + 4),
            Size          = new Size(220, 24),
            DropDownStyle = ComboBoxStyle.DropDownList,
            BackColor     = Theme.Card,
            ForeColor     = Theme.TextMain,
            FlatStyle     = FlatStyle.Flat,
            Font          = Theme.Body(9),
        };
        dnsCombo.Items.AddRange(new object[]
        {
            "None", "Cloudflare", "Quad9", "Google", "OpenDNS", "AdGuard"
        });
        dnsCombo.SelectedItem = _config.DNS_Provider;
        dnsCombo.SelectedIndexChanged += OnDnsProviderChanged;
        page.Controls.Add(dnsCombo);
        y += 36;

        y = AddSettingCheckbox(page, "DNS_DoH", "Enable DNS over HTTPS", "Encrypt DNS queries (requires compatible provider)", _config.DNS_DoH, y);

        // Final padding so the last setting isn't flush with the bottom edge
        page.Controls.Add(new Panel { Location = new Point(0, y + 24), Size = new Size(1, 1) });

        return page;
    }

    private int AddSectionHeader(Panel page, string text, int y)
    {
        var sep = new Panel
        {
            Location  = new Point(8, y + 4),
            Size      = new Size(840, 1),
            BackColor = Theme.Separator,
        };
        page.Controls.Add(sep);

        var lbl = new Label
        {
            Text      = text,
            Font      = Theme.SectionTitle(),
            ForeColor = Theme.AccentBlue,
            AutoSize  = true,
            Location  = new Point(8, y + 10),
        };
        page.Controls.Add(lbl);
        return y + 38;
    }

    private int AddSettingCheckbox(Panel page, string key, string label, string desc, bool initial, int y)
    {
        var card = new Panel
        {
            Location  = new Point(20, y),
            Size      = new Size(820, 46),
            BackColor = Theme.Card,
        };

        var cb = new CheckBox
        {
            Text      = label,
            Location  = new Point(14, 6),
            Size      = new Size(420, 20),
            Font      = new Font("Segoe UI", 10, FontStyle.Bold),
            ForeColor = Theme.TextMain,
            BackColor = Theme.Card,
            Tag       = key,
            Checked   = initial,
        };
        cb.CheckedChanged += OnSettingsCheckChanged;
        card.Controls.Add(cb);
        _settingsCheckboxes[key] = cb;

        var d = new Label
        {
            Text      = desc,
            Location  = new Point(34, 26),
            Size      = new Size(770, 16),
            Font      = Theme.Body(8),
            ForeColor = Theme.TextDim,
            BackColor = Theme.Card,
        };
        card.Controls.Add(d);

        page.Controls.Add(card);
        return y + 52;
    }

    // ============================================================================
    //  PAGE 5: LOGS
    // ============================================================================
    private Panel BuildLogsPage()
    {
        var page = new Panel { BackColor = Theme.Bg };

        var title = new Label
        {
            Text      = "Log Files",
            Font      = Theme.PageTitle(),
            ForeColor = Theme.Accent,
            AutoSize  = true,
            Location  = new Point(8, 8),
        };
        page.Controls.Add(title);

        var subtitle = new Label
        {
            Text      = "Daily log files written next to the executable. Click any card to open in Notepad.",
            Font      = Theme.Body(9),
            ForeColor = Theme.TextDim,
            AutoSize  = true,
            Location  = new Point(8, 44),
        };
        page.Controls.Add(subtitle);

        var logsDir = Paths.LogsDir;
        var today   = DateTime.Now.ToString("yyyy-MM-dd");
        var entries = new (string Title, string FileName, string Desc)[]
        {
            ("Monitor Log",     $"monitor_{today}.log",     "All baseline + scan-cycle messages"),
            ("Alerts Log",      $"alerts_{today}.log",      "All security alerts dispatched this session"),
            ("Connections Log", $"connections_{today}.log", "Outbound network connections detected"),
            ("Processes Log",   $"processes_{today}.log",   "New process and behavior alerts"),
        };
        int y = 80;
        foreach (var entry in entries)
        {
            var card = new Panel
            {
                Location  = new Point(8, y),
                Size      = new Size(840, 64),
                BackColor = Theme.Card,
                Cursor    = Cursors.Hand,
                Tag       = Path.Combine(logsDir, entry.FileName),
            };
            card.Click += OnOpenFileClick;

            var t = new Label
            {
                Text      = entry.Title,
                Font      = new Font("Segoe UI", 11, FontStyle.Bold),
                ForeColor = Theme.AccentBlue,
                AutoSize  = true,
                Location  = new Point(16, 10),
            };
            t.Click += OnOpenFileClick;
            t.Tag    = card.Tag;
            card.Controls.Add(t);

            var d = new Label
            {
                Text      = entry.Desc + " — " + entry.FileName,
                Font      = Theme.Mono(9),
                ForeColor = Theme.TextDim,
                AutoSize  = true,
                Location  = new Point(16, 34),
            };
            d.Click += OnOpenFileClick;
            d.Tag    = card.Tag;
            card.Controls.Add(d);

            page.Controls.Add(card);
            y += 72;
        }

        return page;
    }

    // ============================================================================
    //  PAGE 6: CONSOLE
    // ============================================================================
    private Panel BuildConsolePage()
    {
        var page = new Panel { BackColor = Theme.Bg };

        var title = new Label
        {
            Text      = "Console Output",
            Font      = Theme.PageTitle(),
            ForeColor = Theme.Accent,
            AutoSize  = true,
            Location  = new Point(8, 8),
        };
        page.Controls.Add(title);

        var clearBtn = new Button
        {
            Text      = "Clear",
            Location  = new Point(8, 50),
            Size      = new Size(100, 30),
            FlatStyle = FlatStyle.Flat,
            BackColor = Theme.BtnHover,
            ForeColor = Theme.TextMain,
            Font      = new Font("Segoe UI", 9, FontStyle.Bold),
            Cursor    = Cursors.Hand,
        };
        clearBtn.FlatAppearance.BorderSize = 0;
        clearBtn.Click += OnClearConsoleClick;
        page.Controls.Add(clearBtn);

        _consoleBox.Location    = new Point(8, 90);
        _consoleBox.Size        = new Size(1000, 540);
        _consoleBox.Anchor      = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        _consoleBox.Font        = Theme.Mono(9);
        _consoleBox.BackColor   = Theme.ConsoleBg;
        _consoleBox.ForeColor   = Theme.ConsoleText;
        _consoleBox.ReadOnly    = true;
        _consoleBox.WordWrap    = false;
        _consoleBox.ScrollBars  = RichTextBoxScrollBars.Both;
        _consoleBox.BorderStyle = BorderStyle.None;
        page.Controls.Add(_consoleBox);

        return page;
    }
}
